language: node_js
node_js:
  # yarn is currently broken on node v10
  # see: https://github.com/yarnpkg/yarn/issues/5727
  # - 'node'
  - 'lts/*'

env:
  - BUILD_ENV=production

notifications:
  email: false

script:
  - NODE_ENV=$BUILD_ENV yarn test --coverage --coverageReporters lcov --runInBand

after_success:
  - yarn coveralls < coverage/lcov.info
